documentation:
  - changed-files:
      - any-glob-to-any-file: ['**/*.md']

ci:
  - changed-files:
      - any-glob-to-any-file: ['.github/workflows/**', '.github/interim/**']

dependencies:
  - changed-files:
      - any-glob-to-any-file: ['.github/dependabot.yml']
